version = 0.1
[default.deploy.parameters]
stack_name = "yt-service"
resolve_s3 = true
s3_prefix = "yt-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["Function=923286072236.dkr.ecr.us-east-1.amazonaws.com/speech_to_text"]
