Description: Get subtitles from video.
Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
    Properties:
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      FunctionName: GetSubtitles
      Description: Get Subtitles for video using yt-dlp
      PackageType: Image
      Timeout: 300
